In [1]:
import numpy as np

In [23]:
A = np.arange(1,10).reshape(3,3)

In [8]:
np.dot(A,A)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [11]:
S = np.array([[1, 0, 0],[1,2,3],[30,36,42]])

In [12]:
np.linalg.det(S)

-24.000000000000004

In [24]:
B = np.array([0,1,0])

In [25]:
A_ = A.T

In [26]:
np.dot(B,A_)

array([2, 5, 8])

In [27]:
np.dot(B,np.dot(A_,A_))

array([ 36,  81, 126])

In [18]:
-2*126+8*36

36

In [28]:
S_ = np.array([-B,np.dot(B,A_),-np.dot(B,np.dot(A_,A_))])

In [30]:
S_

array([[   0,   -1,    0],
       [   2,    5,    8],
       [ -36,  -81, -126]])

In [31]:
np.linalg.det(S_)

36.0

In [32]:
1/2*np.sqrt(0.4/4)

0.15811388300841897